---
- hosts: local
  remote_user: root
  connection: local
  roles:
    - role: ansible-keycloak
      become: yes
  vars:
    keycloak_config_dir: standalone/configuration
    keycloak_postgres_username: tkpproxies
    keycloak_postgres_password: PbnppPaGdD87u9mzvat3nzBgT3mhLB
    keycloak_postgres_url: 10.21.39.135
    keycloak_postgres_port: 5432
    keycloak_postgres_db: tokopedia-proxies
    keycloak_service_user: root
    keycloak_service_group: root
    infinispan_address: 10.21.40.95
    infinispan_username: admin
    infinispan_password: admin