---
- name: check for existing install...
  become: yes
  become_user: root
  stat:
    path: '{{ keycloak_install_dir }}'
  changed_when: False
  register: keycloak_binary
  tags: setup
- when: not keycloak_binary.stat.exists
  block:
    - name: download tgz
      become: yes
      become_user: root
      get_url:
        url: '{{ keycloak_tgz_url }}'
        dest: /tmp/{{ keycloak_tgz }}
        checksum: '{{ keycloak_checksum }}'
        mode: 0644
      tags: setup
    - name: unarchive
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ keycloak_tgz }}
        dest: '{{ keycloak_parent_install_dir }}'
        creates: '{{ keycloak_install_dir }}'
      tags: setup
  always:
    - name: cleanup...
      become: yes
      become_user: root
      file:
        path: /tmp/{{ keycloak_tgz }}
        state: absent
      tags: setup

- name: link
  become: yes
  become_user: root
  file:
    src: '{{ keycloak_install_dir }}'
    dest: '{{ keycloak_link_dir }}'
    state: link
  tags: setup

- name: check for JDBC driver...
  become: yes
  become_user: root
  stat:
    path: '{{ keycloak_install_dir }}/{{ keycloak_jdbc_module_dir }}/{{ keycloak_jdbc_version }}.jar'
  changed_when: False
  register: jdbc_module
  tags: setup

- when: not jdbc_module.stat.exists
  block:
    - name: create jdbc module directory
      file:
        path: '{{ keycloak_link_dir }}/{{ keycloak_jdbc_module_dir }}'
        state: directory
      tags: setup

    - name: download jdbc module...
      become: yes
      get_url:
        url: '{{ keycloak_jdbc_url }}/postgresql-{{ keycloak_jdbc_version }}.jar'
        dest: '{{ keycloak_link_dir }}/{{ keycloak_jdbc_module_dir }}/postgresql-{{ keycloak_jdbc_version }}.jar'
        checksum: '{{ keycloak_jdbc_checksum }}'
        mode: 0644
      tags: setup

- name: create JDBC module.xml
  template:
    src: module.xml.j2
    dest: '{{ keycloak_link_dir }}/{{ keycloak_jdbc_module_dir }}/module.xml'
    mode: '0644'
  tags: [setup, update]

- name: copy standalone-ha.xml
  template: 
    src: standalone-ha.xml.j2
    dest: '{{ keycloak_link_dir }}/{{ keycloak_config_dir }}/standalone-ha.xml'
    mode: 0644
  tags: [setup, update]

- name: copy add-user-keycloak-custom.sh.j2
  template: 
    src: add-user-keycloak-custom.sh.j2
    dest: '{{ keycloak_link_dir }}/bin/add-user-keycloak-custom.sh'
    mode: 0644
  tags: [setup, update]

- name: add to path
  become: yes
  become_user: root
  with_items:
    - f: keycloak.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
  tags: [setup, update]

- name: configure systemd
  template:
    src: keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - reload systemd
    - restart keycloak
  tags: [setup, update]

- name: restart keycloak for tags update
  systemd:
    state: restarted
    daemon_reload: yes
    name: keycloak
  tags: [never, update]
  
- meta: flush_handlers
