---
keycloak_name: keycloak-{{ keycloak_ver }}
keycloak_tgz: '{{ keycloak_name }}.tar.gz'
keycloak_wilfdly_tgz: '{{ keycloak_name }}-legacy.tar.gz'
keycloak_tgz_url: '{{ keycloak_mirror }}/{{ keycloak_ver }}/{{ keycloak_wilfdly_tgz }}'
keycloak_checksum: '{{ keycloak_checksums[keycloak_ver] }}'

keycloak_install_dir: '{{ keycloak_parent_install_dir }}/{{ keycloak_name }}'
keycloak_link_dir: '{{ keycloak_parent_install_dir }}/keycloak'
